#!/usr/bin/env python3
"""
DarkPen Quick Start Guide
Shows exactly how to use the CLI interface
"""

def show_quick_start():
    print("🚀 DarkPen Quick Start Guide")
    print("=" * 50)
    print()
    print("📋 STEP-BY-STEP USAGE:")
    print()
    print("1️⃣  START THE APP:")
    print("   python3 darkpen_cli.py")
    print()
    print("2️⃣  SEE AVAILABLE COMMANDS:")
    print("   DarkPen> help")
    print()
    print("3️⃣  LIST MODULES:")
    print("   DarkPen> modules")
    print()
    print("4️⃣  SELECT A MODULE:")
    print("   DarkPen> select 1")
    print("   (This selects EternalBlue exploit)")
    print()
    print("5️⃣  SET YOUR TARGET:")
    print("   DarkPen> target")
    print("   Enter target IP/hostname: 192.168.1.100")
    print("   Enter port: 445")
    print()
    print("6️⃣  CHECK VULNERABILITY:")
    print("   DarkPen> check")
    print()
    print("7️⃣  RUN EXPLOIT:")
    print("   DarkPen> exploit")
    print()
    print("8️⃣  VIEW SESSIONS:")
    print("   DarkPen> sessions")
    print()
    print("9️⃣  EXIT:")
    print("   DarkPen> quit")
    print()
    print("💡 COMMON COMMANDS:")
    print("   help       - Show all commands")
    print("   modules    - List exploit modules")
    print("   select     - Choose a module")
    print("   target     - Set target IP/port")
    print("   check      - Test vulnerability")
    print("   exploit    - Run the attack")
    print("   sessions   - View active sessions")
    print("   quit       - Exit the app")
    print()
    print("⚠️  IMPORTANT:")
    print("   - Only use on systems you own or have permission to test")
    print("   - The CLI is faster and more reliable than GUI")
    print("   - All Metasploit functionality is available")
    print()
    print("✅ Ready to start? Run: python3 darkpen_cli.py")

if __name__ == "__main__":
    show_quick_start() 